### ISSUE TITLE
Update README with links that works

### ISSUE THREAD

**Issue by ASAPSegfault** [massalabs/massa-cloud-simulator#13]
The link to the docker installation page is not present on the "here"
The link to the Python3 download page is not present on the "here"

**Comment by Reda-R** [comment]
Thanks for reviewing the readme file ! It's fixed 👍

**Comment by sydhds** [comment]
@ASAPSegfault Readme file has been updated in main branch. Would you have having a look at it and report any issue ?

**Comment by ASAPSegfault** [comment]
I had a look, the issue I mentioned is fixed, I tried to follow the full procedure but I cannot as Docker daemon is not starting on my Windows for some reason. Will troubleshoot and let you know once I've managed to follow the whole procedure.

**Comment by ASAPSegfault** [comment]
I managed to follow the procedure, and here is what I get by the end of the launch.sh process :

![image](https://user-images.githubusercontent.com/45430752/216638625-71641a0f-d684-40da-a6b5-f159c7a0fa9a.png)

Do you want me to create another issue for this specific topic?

Otherwise the readme looks good to me.

**Comment by sydhds** [comment]
> I managed to follow the procedure, and here is what I get by the end of the launch.sh process :
> 
> ![image](https://user-images.githubusercontent.com/45430752/216638625-71641a0f-d684-40da-a6b5-f159c7a0fa9a.png)
> 
> Do you want me to create another issue for this specific topic?
> 
> Otherwise the readme looks good to me.

Would you mind updating your main branch and testing it again? If the bug is still there, yes please open a new issue :)

**Comment by ASAPSegfault** [comment]
Created here : https://github.com/massalabs/massa-cloud-simulator/issues/19

**Comment by sydhds** [comment]
Closing it as a new issue has been opened
